server:
    port: 8888
spring:
    profiles:
        active: git
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/RebeldeCuantico/online-store-ddd-config.git
                    default-label: main
