apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:16686/
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: jaeger

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsondata:
        httpMethod: POST
        exemplarTraceIdDestinations:        
        - datasourceUid: my_jaeger_uid
          name: trace_id
        - name: trace_id
          url: 'http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Jaeger%22,%7B%22query%22:%22$${__value.raw}%22%7D%5D'

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
        derivedFields:
          - datasourceUid: jaeger
            matcherRegex: (?:"TraceId"):"(\w+)"
            name: TraceID
            url: $${__value.raw}